services:
  openvpn:
    image: arsartori/openvpn:latest
    container_name: openvpn
    hostname: openvpn
    restart: always
    ports:
      - 1194:1194/udp
    volumes:
      - /opt/docker/openvpn:/etc/openvpn
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=America/Sao_Paulo
